[build]
  # Build command
  command = "cd admin-panel/frontend && npm run build"
  
  # Directory to publish
  publish = "admin-panel/frontend/build"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  
  # Python version for functions
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# API routes to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.netlify.com"

# Environment variables (set in Netlify dashboard)
[context.production.environment]
  REACT_APP_API_URL = "/.netlify/functions"
  REACT_APP_ENV = "production"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "/.netlify/functions"
  REACT_APP_ENV = "preview"
